server:
  port: 8080
  address: localhost

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1q2w3e4r!!B

  jpa:
    hibernate:
      ddl-auto: update # (1) ??? ?? ??  update -> create 변ㄱ
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql