server:
  port: 8080
  address:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/triviewer?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: create # (1) ??? ?? ??  update -> create 변ㄱ
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 838144333786-ols4gqq7crt0dv2e9iah6mnri8jh39nf.apps.googleusercontent.com           # (1)
            clientSecret: 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  # (2)

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

cloud: #S3 업로드
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}
    s3:
      bucket: ${S3_BUCKET}
#      endpoint: ${S3_ENDPOINT}
    region:
      static: ${S3_REGION} #ap-northeast-2
    stack:
      auto: false # Not using CloudFormation.
  servlet: #S3 - Limit file size.
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB